import { create } from 'zustand';

export const useBattleStore = create((set) => ({
  view: 'battle',
  activeMode: 'selection',
  roomId: '',
  isOnline: navigator.onLine,
  isCloudLoading: true,
  savingStreak: 0,
  streakBroken: false,
  teamSpentDaily: 0,
  teamSpentWeekly: 0,
  teamSpentMonthly: 0,
  enemySpentDaily: -1,
  enemySpentWeekly: -1,
  enemySpentMonthly: -1,
  activeChallenges: [],
  claimedAvoidedItems: [],
  isSevered: false,
  battleLog: [],
  aiComment: '...',
  isAiProcessing: false,
  pendingTx: null,
  reflectionText: '',
  coldWarEndTime: null,
  showBudgetSetup: false,
  showShop: false,
  showCustomModal: false,
  showAchievements: false,
  showEvolutionPath: false,
  showFriends: false,
  showRoomInput: false,
  showInviteQR: false,
  lastPersonaSwitch: null,
  now: Date.now(),
  achievementNotification: null,
  lastTrackDate: (() => { try { return JSON.parse(localStorage.getItem('bb_v4_lastTrack')); } catch { return null; } })(),
  nlpInput: '',
  bannerText: '',
  hasCompletedTutorial: (() => { try { return JSON.parse(localStorage.getItem('bb_v4_tutorial_done')); } catch { return false; } })() ?? false,
  showTutorial: false,
  showLogin: false,

  setView: (valOrFn) => set((state) => ({ view: typeof valOrFn === 'function' ? valOrFn(state.view) : valOrFn })),
  setActiveMode: (valOrFn) => set((state) => ({ activeMode: typeof valOrFn === 'function' ? valOrFn(state.activeMode) : valOrFn })),
  setRoomId: (valOrFn) => set((state) => ({ roomId: typeof valOrFn === 'function' ? valOrFn(state.roomId) : valOrFn })),
  setIsOnline: (valOrFn) => set((state) => ({ isOnline: typeof valOrFn === 'function' ? valOrFn(state.isOnline) : valOrFn })),
  setIsCloudLoading: (valOrFn) => set((state) => ({ isCloudLoading: typeof valOrFn === 'function' ? valOrFn(state.isCloudLoading) : valOrFn })),
  setSavingStreak: (valOrFn) => set((state) => ({ savingStreak: typeof valOrFn === 'function' ? valOrFn(state.savingStreak) : valOrFn })),
  setStreakBroken: (valOrFn) => set((state) => ({ streakBroken: typeof valOrFn === 'function' ? valOrFn(state.streakBroken) : valOrFn })),
  setTeamSpentDaily: (valOrFn) => set((state) => ({ teamSpentDaily: typeof valOrFn === 'function' ? valOrFn(state.teamSpentDaily) : valOrFn })),
  setTeamSpentWeekly: (valOrFn) => set((state) => ({ teamSpentWeekly: typeof valOrFn === 'function' ? valOrFn(state.teamSpentWeekly) : valOrFn })),
  setTeamSpentMonthly: (valOrFn) => set((state) => ({ teamSpentMonthly: typeof valOrFn === 'function' ? valOrFn(state.teamSpentMonthly) : valOrFn })),
  setEnemySpentDaily: (valOrFn) => set((state) => ({ enemySpentDaily: typeof valOrFn === 'function' ? valOrFn(state.enemySpentDaily) : valOrFn })),
  setEnemySpentWeekly: (valOrFn) => set((state) => ({ enemySpentWeekly: typeof valOrFn === 'function' ? valOrFn(state.enemySpentWeekly) : valOrFn })),
  setEnemySpentMonthly: (valOrFn) => set((state) => ({ enemySpentMonthly: typeof valOrFn === 'function' ? valOrFn(state.enemySpentMonthly) : valOrFn })),
  setActiveChallenges: (valOrFn) => set((state) => ({ activeChallenges: typeof valOrFn === 'function' ? valOrFn(state.activeChallenges) : valOrFn })),
  setClaimedAvoidedItems: (valOrFn) => set((state) => ({ claimedAvoidedItems: typeof valOrFn === 'function' ? valOrFn(state.claimedAvoidedItems) : valOrFn })),
  setIsSevered: (valOrFn) => set((state) => ({ isSevered: typeof valOrFn === 'function' ? valOrFn(state.isSevered) : valOrFn })),
  setBattleLog: (valOrFn) => set((state) => ({ battleLog: typeof valOrFn === 'function' ? valOrFn(state.battleLog) : valOrFn })),
  addToBattleLog: (entry) => set((state) => {
    const next = [entry, ...state.battleLog].slice(0, 200);
    return { battleLog: next };
  }),
  setAiComment: (valOrFn) => set((state) => ({ aiComment: typeof valOrFn === 'function' ? valOrFn(state.aiComment) : valOrFn })),
  setIsAiProcessing: (valOrFn) => set((state) => ({ isAiProcessing: typeof valOrFn === 'function' ? valOrFn(state.isAiProcessing) : valOrFn })),
  setPendingTx: (valOrFn) => set((state) => ({ pendingTx: typeof valOrFn === 'function' ? valOrFn(state.pendingTx) : valOrFn })),
  setReflectionText: (valOrFn) => set((state) => ({ reflectionText: typeof valOrFn === 'function' ? valOrFn(state.reflectionText) : valOrFn })),
  setColdWarEndTime: (valOrFn) => set((state) => ({ coldWarEndTime: typeof valOrFn === 'function' ? valOrFn(state.coldWarEndTime) : valOrFn })),
  setShowBudgetSetup: (valOrFn) => set((state) => ({ showBudgetSetup: typeof valOrFn === 'function' ? valOrFn(state.showBudgetSetup) : valOrFn })),
  setShowShop: (valOrFn) => set((state) => ({ showShop: typeof valOrFn === 'function' ? valOrFn(state.showShop) : valOrFn })),
  setShowCustomModal: (valOrFn) => set((state) => ({ showCustomModal: typeof valOrFn === 'function' ? valOrFn(state.showCustomModal) : valOrFn })),
  setShowAchievements: (valOrFn) => set((state) => ({ showAchievements: typeof valOrFn === 'function' ? valOrFn(state.showAchievements) : valOrFn })),
  setShowEvolutionPath: (valOrFn) => set((state) => ({ showEvolutionPath: typeof valOrFn === 'function' ? valOrFn(state.showEvolutionPath) : valOrFn })),
  setShowFriends: (valOrFn) => set((state) => ({ showFriends: typeof valOrFn === 'function' ? valOrFn(state.showFriends) : valOrFn })),
  setShowRoomInput: (valOrFn) => set((state) => ({ showRoomInput: typeof valOrFn === 'function' ? valOrFn(state.showRoomInput) : valOrFn })),
  setShowInviteQR: (valOrFn) => set((state) => ({ showInviteQR: typeof valOrFn === 'function' ? valOrFn(state.showInviteQR) : valOrFn })),
  setLastPersonaSwitch: (valOrFn) => set((state) => ({ lastPersonaSwitch: typeof valOrFn === 'function' ? valOrFn(state.lastPersonaSwitch) : valOrFn })),
  setNow: (valOrFn) => set((state) => ({ now: typeof valOrFn === 'function' ? valOrFn(state.now) : valOrFn })),
  setAchievementNotification: (valOrFn) => set((state) => ({ achievementNotification: typeof valOrFn === 'function' ? valOrFn(state.achievementNotification) : valOrFn })),
  setLastTrackDate: (valOrFn) => set((state) => {
    const next = typeof valOrFn === 'function' ? valOrFn(state.lastTrackDate) : valOrFn;
    localStorage.setItem('bb_v4_lastTrack', JSON.stringify(next));
    return { lastTrackDate: next };
  }),
  setNlpInput: (valOrFn) => set((state) => ({ nlpInput: typeof valOrFn === 'function' ? valOrFn(state.nlpInput) : valOrFn })),
  setBannerText: (valOrFn) => set((state) => ({ bannerText: typeof valOrFn === 'function' ? valOrFn(state.bannerText) : valOrFn })),
  setHasCompletedTutorial: (valOrFn) => set((state) => {
    const next = typeof valOrFn === 'function' ? valOrFn(state.hasCompletedTutorial) : valOrFn;
    localStorage.setItem('bb_v4_tutorial_done', JSON.stringify(next));
    return { hasCompletedTutorial: next };
  }),
  setShowTutorial: (valOrFn) => set((state) => ({ showTutorial: typeof valOrFn === 'function' ? valOrFn(state.showTutorial) : valOrFn })),
  setShowLogin: (valOrFn) => set((state) => ({ showLogin: typeof valOrFn === 'function' ? valOrFn(state.showLogin) : valOrFn })),
}));
